name: certbot-dns-wedos
version: '2.3.0'
summary: Wedos DNS Authenticator plugin for Certbot
description: Wedos DNS Authenticator plugin for Certbot
website: https://github.com/clazzor/certbot-dns-wedos
license: Apache-2.0
base: core22
#base: core24
grade: stable
confinement: strict
adopt-info: certbot-dns-wedos
#platforms:
#  amd64:
#  arm64:
#  armhf:
architectures:
#  - build-on: amd64
#  - build-on: arm64
  - build-on: armhf

parts:
#  install-rust:
#    plugin: nil
#    override-pull: |
#      if [ "$SNAP_ARCH" = "armhf" ]; then
#        apt-get update
#        apt-get -y install curl
#        curl https://sh.rustup.rs -sSf | sh -s -- -y
#      fi
  certbot-dns-wedos:
    plugin: python
    source: .
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version $SNAPCRAFT_PART_SRC/setup.py | cut -f2 -d= | tr -d '"[:space:]'`
    build-environment:
      - SNAP_BUILD: "True"
    build-packages:
      - gcc
#      - git
#      - build-essential
      - libffi-dev
      - libssl-dev
      - cargo
#      - clang
      - pkg-config
      - python3-dev
#    after: [install-rust]
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        snapcraftctl pull
        mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
