name: certbot-dns-wedos
version: '2.3.0'
summary: Wedos DNS Authenticator plugin for Certbot
description: Wedos DNS Authenticator plugin for Certbot
website: https://github.com/clazzor/certbot-dns-wedos
license: Apache-2.0 license 
base: core20
grade: stable
confinement: strict
adopt-info: certbot-dns-wedos
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  certbot-dns-wedos:
    plugin: python
    source: .
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version $SNAPCRAFT_PART_SRC/setup.py | cut -f2 -d= | tr -d '"[:space:]'`
    build-environment:
      - SNAP_BUILD: "True"
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        snapcraftctl pull
        mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
